name: Generate .env File
on:
  push:
    branches:
      - main
jobs:
  generate-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate .env file
        run: |
          echo "FIREBASE_KEY=${{ secrets.FIREBASE_KEY }}" >> .env
          echo "MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }}" >> .env
          echo "APP_ID=${{ secrets.APP_ID }}" >> .env
        shell: bash
